services:
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  ministack:
    image: ministackorg/ministack:latest
    container_name: infra_ministack
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - lambda-docker-volume:/var/task
    networks:
      ecommerce-net:
        ipv4_address: 10.0.2.20  # IP fija — cdk-deployer la usa como DNS

  cdk-deployer:
    image: node:22-alpine
    container_name: ecommerce-cdk-deployer
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://10.0.2.20:4566
      AWS_ENDPOINT_URL_S3: http://10.0.2.20:4566
      CDK_DEFAULT_ACCOUNT: "000000000000"
      CDK_DEFAULT_REGION: us-east-1
      JSII_SILENCE_WARNING_DEPRECATED_NODE_VERSION: "1"
      HOME: /tmp
    dns:
      - 10.0.2.20
      - 8.8.8.8
    depends_on:
      - ministack
    command: ["tail", "-f", "/dev/null"]
    networks:
      - ecommerce-net

  frontend:
    image: node:22-alpine
    container_name: ecommerce-frontend
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    environment:
      VITE_API_PROXY_TARGET: http://10.0.2.20:4566
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
    name: ecommerce-net
    ipam:
      config:
        - subnet: 10.0.2.0/24  # requerido para asignar IPs fijas

volumes:
  lambda-docker-volume:
    driver: local
